<template>
  <div class="env-setup-panel">
    <div class="scroll-container">
      <!-- Step 01: 模拟实例初始化 -->
      <StepInstanceInit
        :phase="phase"
        :simulation-id="currentSimulationId"
        :project-data="projectData"
        :task-id="taskId"
      />

      <!-- Step 02: 生成 Agent 人设 -->
      <StepAgentProfiles
        :phase="phase"
        :prepare-progress="prepareProgress"
        :profiles="profiles"
        :expected-total="expectedTotal"
        @select-profile="selectProfile"
      />

      <!-- Step 03: 生成双平台模拟配置 -->
      <StepSimulationConfig
        :phase="phase"
        :simulation-config="simulationConfig"
      />

      <!-- Step 04: 初始激活编排 -->
      <StepActionOrchestration
        :phase="phase"
        :event-config="simulationConfig?.event_config"
        :profiles="profiles"
      />

      <!-- Step 05: 准备完成 -->
      <StepAutoPilotConfig
        :phase="phase"
        :simulation-config="simulationConfig"
        :simulation-mode="simulationMode"
        :simulation-rounds="simulationRounds"
        @go-back="$emit('go-back')"
        @start-simulation="handleStartSimulation"
      />
    </div>

    <!-- Profile Detail Modal -->
    <ProfileDetailModal
      :profile="selectedProfile"
      @close="selectedProfile = null"
    />

    <!-- Bottom Info / Logs -->
    <div class="system-logs">
      <div class="log-header">
        <span class="log-title">SYSTEM DASHBOARD</span>
        <span class="log-id">{{ simulationId || 'NO_SIMULATION' }}</span>
      </div>
      <div class="log-content" ref="logContent">
        <div class="log-line" v-for="(log, idx) in systemLogs" :key="idx">
          <span class="log-time">{{ log.time }}</span>
          <span class="log-msg">{{ log.msg }}</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, watch, onMounted, onUnmounted, nextTick } from 'vue'
import { 
  prepareSimulation, 
  getPrepareStatus, 
  getSimulationProfilesRealtime,
  getSimulationConfigRealtime 
} from '../api/simulation'

// 导入子组件
import StepInstanceInit from './env-setup/StepInstanceInit.vue'
import StepAgentProfiles from './env-setup/StepAgentProfiles.vue'
import StepSimulationConfig from './env-setup/StepSimulationConfig.vue'
import StepActionOrchestration from './env-setup/StepActionOrchestration.vue'
import StepAutoPilotConfig from './env-setup/StepAutoPilotConfig.vue'
import ProfileDetailModal from './env-setup/ProfileDetailModal.vue'

const props = defineProps({
  simulationId: String,
  projectData: Object,
  graphData: Object,
  systemLogs: Array,
  simulationMode: String,
  simulationRounds: Number
})

const emit = defineEmits(['go-back', 'next-step', 'add-log', 'update-status', 'update-simulation-id'])

// State
const localSimulationId = ref(props.simulationId)
const currentSimulationId = computed(() => props.simulationId || localSimulationId.value)
const phase = ref(0) // 0: 初始化, 1: 生成人设, 2: 生成配置, 3: 编排, 4: 完成
const taskId = ref(null)
const prepareProgress = ref(0)
const currentStage = ref('')
const profiles = ref([])
const expectedTotal = ref(null)
const simulationConfig = ref(null)
const selectedProfile = ref(null)

// 日志去重：记录上一次输出的关键信息
let lastLoggedMessage = ''
let lastLoggedProfileCount = 0
let lastLoggedConfigStage = ''

// Watch stage to update phase
watch(currentStage, (newStage) => {
  if (newStage === '生成Agent人设' || newStage === 'generating_profiles') {
    phase.value = 1
  } else if (newStage === '生成模拟配置' || newStage === 'generating_config') {
    phase.value = 2
    // 进入配置生成阶段，开始轮询配置
    if (!configTimer) {
      addLog('开始生成双平台模拟配置...')
      startConfigPolling()
    }
  } else if (newStage === '准备模拟脚本' || newStage === 'copying_scripts') {
    phase.value = 2 // 仍属于配置阶段
  }
})

// 从配置中计算自动生成的轮数
const autoGeneratedRounds = computed(() => {
  if (!simulationConfig.value?.time_config) {
    return null
  }
  const totalHours = simulationConfig.value.time_config.total_simulation_hours
  const minutesPerRound = simulationConfig.value.time_config.minutes_per_round
  if (!totalHours || !minutesPerRound) {
    return null
  }
  const calculatedRounds = Math.floor((totalHours * 60) / minutesPerRound)
  return Math.max(calculatedRounds, 40)
})

// Polling timer
let pollTimer = null
let profilesTimer = null
let configTimer = null

// Methods
const addLog = (msg) => {
  emit('add-log', msg)
}

// 处理开始模拟按钮点击
const handleStartSimulation = (params) => {
  if (params?.maxRounds) {
    addLog(`开始模拟，轮数: ${params.maxRounds} 轮`)
  } else {
    addLog(`开始模拟，使用自动配置轮数: ${autoGeneratedRounds.value} 轮`)
  }
  emit('next-step', params)
}

// 自动驾驶逻辑：监听阶段变化
watch(() => phase.value, (newPhase) => {
  if (newPhase === 4 && props.simulationMode === 'auto') {
    addLog('Auto-Pilot: Environment setup completed. Starting simulation in 3s...')
    setTimeout(() => {
      handleStartSimulation({ maxRounds: props.simulationRounds || autoGeneratedRounds.value || 15 })
    }, 3000)
  }
})

const selectProfile = (profile) => {
  selectedProfile.value = profile
}

// 自动开始准备模拟
const startPrepareSimulation = async () => {
  if (!props.simulationId) {
    addLog('错误：缺少 simulationId')
    emit('update-status', 'error')
    return
  }
  
  // 标记第一步完成，开始第二步
  phase.value = 1
  addLog(`模拟实例已创建: ${props.simulationId}`)
  addLog('正在准备模拟环境...')
  emit('update-status', 'processing')
  
  try {
    const res = await prepareSimulation({
      simulation_id: props.simulationId,
      use_llm_for_profiles: true,
      parallel_profile_count: 5
    })
    
    if (res.success && res.data) {
      if (res.data.already_prepared) {
        addLog('检测到已有完成的准备工作，直接使用')
        await loadPreparedData()
        return
      }
      
      taskId.value = res.data.task_id
      addLog(`准备任务已启动`)
      addLog(`  └─ Task ID: ${res.data.task_id}`)
      
      // 立即设置预期Agent总数
      if (res.data.expected_entities_count) {
        expectedTotal.value = res.data.expected_entities_count
        addLog(`从Zep图谱读取到 ${res.data.expected_entities_count} 个实体`)
        if (res.data.entity_types && res.data.entity_types.length > 0) {
          addLog(`  └─ 实体类型: ${res.data.entity_types.join(', ')}`)
        }
      }
      
      addLog('开始轮询准备进度...')
      startPolling()
      startProfilesPolling()
    } else {
      addLog(`准备失败: ${res.error || '未知错误'}`)
      emit('update-status', 'error')
    }
  } catch (err) {
    addLog(`准备异常: ${err.message}`)
    emit('update-status', 'error')
  }
}

const startPolling = () => {
  pollTimer = setInterval(pollPrepareStatus, 2000)
}

const stopPolling = () => {
  if (pollTimer) {
    clearInterval(pollTimer)
    pollTimer = null
  }
}

const startProfilesPolling = () => {
  profilesTimer = setInterval(fetchProfilesRealtime, 3000)
}

const stopProfilesPolling = () => {
  if (profilesTimer) {
    clearInterval(profilesTimer)
    profilesTimer = null
  }
}

const pollPrepareStatus = async () => {
  if (!taskId.value && !props.simulationId) return
  
  try {
    const res = await getPrepareStatus({
      task_id: taskId.value,
      simulation_id: props.simulationId
    })
    
    if (res.success && res.data) {
      const data = res.data
      
      // 更新进度
      prepareProgress.value = data.progress || 0
      
      // 解析阶段信息并输出详细日志
      if (data.progress_detail) {
        currentStage.value = data.progress_detail.current_stage_name || ''
        
        // 输出详细进度日志（避免重复）
        const detail = data.progress_detail
        const logKey = `${detail.current_stage}-${detail.current_item}-${detail.total_items}`
        if (logKey !== lastLoggedMessage && detail.item_description) {
          lastLoggedMessage = logKey
          const stageInfo = `[${detail.stage_index}/${detail.total_stages}]`
          if (detail.total_items > 0) {
            addLog(`${stageInfo} ${detail.current_stage_name}: ${detail.current_item}/${detail.total_items} - ${detail.item_description}`)
          } else {
            addLog(`${stageInfo} ${detail.current_stage_name}: ${detail.item_description}`)
          }
        }
      } else if (data.message) {
        // 从消息中提取阶段
        const match = data.message.match(/\[(\d+)\/(\d+)\]\s*([^:]+)/)
        if (match) {
          currentStage.value = match[3].trim()
        }
        if (data.message !== lastLoggedMessage) {
          lastLoggedMessage = data.message
          addLog(data.message)
        }
      }
      
      // 检查是否完成
      if (data.status === 'completed' || data.status === 'ready' || data.already_prepared) {
        addLog('✓ 准备工作已完成')
        stopPolling()
        stopProfilesPolling()
        await loadPreparedData()
      } else if (data.status === 'failed') {
        addLog(`✗ 准备失败: ${data.error || '未知错误'}`)
        stopPolling()
        stopProfilesPolling()
      }
    }
  } catch (err) {
    console.warn('轮询状态失败:', err)
  }
}

const fetchProfilesRealtime = async () => {
  if (!props.simulationId) return
  
  try {
    const res = await getSimulationProfilesRealtime(props.simulationId, 'reddit')
    
    if (res.success && res.data) {
      profiles.value = res.data.profiles || []
      expectedTotal.value = res.data.total_expected
      
      // 输出 Profile 生成进度日志（仅当数量变化时）
      const currentCount = profiles.value.length
      if (currentCount > 0 && currentCount !== lastLoggedProfileCount) {
        lastLoggedProfileCount = currentCount
        const total = expectedTotal.value || '?'
        const latestProfile = profiles.value[currentCount - 1]
        const profileName = latestProfile?.name || latestProfile?.username || `Agent_${currentCount}`
        if (currentCount === 1) {
          addLog(`开始生成Agent人设...`)
        }
        addLog(`→ Agent人设 ${currentCount}/${total}: ${profileName} (${latestProfile?.profession || '未知职业'})`)
        
        if (expectedTotal.value && currentCount >= expectedTotal.value) {
          addLog(`✓ 全部 ${currentCount} 个Agent人设生成完成`)
        }
      }
    }
  } catch (err) {
    console.warn('获取 Profiles 失败:', err)
  }
}

// 配置轮询
const startConfigPolling = () => {
  configTimer = setInterval(fetchConfigRealtime, 2000)
}

const stopConfigPolling = () => {
  if (configTimer) {
    clearInterval(configTimer)
    configTimer = null
  }
}

const fetchConfigRealtime = async () => {
  if (!props.simulationId) return
  
  try {
    const res = await getSimulationConfigRealtime(props.simulationId)
    
    if (res.success && res.data) {
      const data = res.data
      
      // 输出配置生成阶段日志（避免重复）
      if (data.generation_stage && data.generation_stage !== lastLoggedConfigStage) {
        lastLoggedConfigStage = data.generation_stage
        if (data.generation_stage === 'generating_profiles') {
          addLog('正在生成Agent人设配置...')
        } else if (data.generation_stage === 'generating_config') {
          addLog('正在调用LLM生成模拟配置参数...')
        }
      }
      
      // 如果配置已生成
      if (data.config_generated && data.config) {
        simulationConfig.value = data.config
        addLog('✓ 模拟配置生成完成')
        
        if (data.summary) {
          addLog(`  ├─ Agent数量: ${data.summary.total_agents}个`)
          addLog(`  ├─ 模拟时长: ${data.summary.simulation_hours}小时`)
          addLog(`  ├─ 初始帖子: ${data.summary.initial_posts_count}条`)
          addLog(`  ├─ 热点话题: ${data.summary.hot_topics_count}个`)
          addLog(`  └─ 平台配置: Twitter ${data.summary.has_twitter_config ? '✓' : '✗'}, Reddit ${data.summary.has_reddit_config ? '✓' : '✗'}`)
        }
        
        if (data.config.time_config) {
          const tc = data.config.time_config
          addLog(`时间配置: 每轮${tc.minutes_per_round}分钟, 共${Math.floor((tc.total_simulation_hours * 60) / tc.minutes_per_round)}轮`)
        }
        
        if (data.config.event_config?.narrative_direction) {
          const narrative = data.config.event_config.narrative_direction
          addLog(`叙事方向: ${narrative.length > 50 ? narrative.substring(0, 50) + '...' : narrative}`)
        }
        
        stopConfigPolling()
        phase.value = 4
        addLog('✓ 环境搭建完成，可以开始模拟')
        emit('update-status', 'completed')
      }
    }
  } catch (err) {
    console.warn('获取 Config 失败:', err)
  }
}

const loadPreparedData = async () => {
  phase.value = 2
  addLog('正在加载已有配置数据...')

  await fetchProfilesRealtime()
  addLog(`已加载 ${profiles.value.length} 个Agent人设`)

  try {
    const res = await getSimulationConfigRealtime(currentSimulationId.value)
    if (res.success && res.data) {
      if (res.data.config_generated && res.data.config) {
        simulationConfig.value = res.data.config
        addLog('✓ 模拟配置加载成功')
        
        if (res.data.summary) {
          addLog(`  ├─ Agent数量: ${res.data.summary.total_agents}个`)
          addLog(`  ├─ 模拟时长: ${res.data.summary.simulation_hours}小时`)
          addLog(`  └─ 初始帖子: ${res.data.summary.initial_posts_count}条`)
        }
        
        addLog('✓ 环境搭建完成，可以开始模拟')
        phase.value = 4
        emit('update-status', 'completed')
      } else {
        addLog('配置生成中，开始轮询等待...')
        startConfigPolling()
      }
    } else {
      // 如果配置接口返回失败，但模拟已准备完成，仍然设置为完成状态
      addLog('配置数据加载失败，但模拟环境已准备完成')
      phase.value = 4
      emit('update-status', 'completed')
    }
  } catch (err) {
    addLog(`加载配置失败: ${err.message}`)
    // 即使配置加载失败，如果模拟已准备完成，仍然设置为完成状态
    addLog('但模拟环境已准备完成，可以开始模拟')
    phase.value = 4
    emit('update-status', 'completed')
  }
}

// Scroll log to bottom
const logContent = ref(null)
watch(() => props.systemLogs?.length, () => {
  nextTick(() => {
    if (logContent.value) {
      logContent.value.scrollTop = logContent.value.scrollHeight
    }
  })
})

onMounted(() => {
  addLog('Step2 环境搭建初始化')
  startPrepareSimulation()
})

onUnmounted(() => {
  stopPolling()
  stopProfilesPolling()
  stopConfigPolling()
})
</script>

<style scoped>
.env-setup-panel {
  height: 100%;
  display: flex;
  flex-direction: column;
  background: #FAFAFA;
  font-family: 'Space Grotesk', 'Noto Sans SC', system-ui, sans-serif;
}

.scroll-container {
  flex: 1;
  overflow-y: auto;
  padding: 24px;
  display: flex;
  flex-direction: column;
  gap: 16px;
}

/* System Logs */
.system-logs {
  background: #1a1a1a;
  border-top: 1px solid #333;
  flex-shrink: 0;
}

.log-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 8px 16px;
  background: #111;
  border-bottom: 1px solid #333;
}

.log-title {
  font-family: 'JetBrains Mono', monospace;
  font-size: 10px;
  font-weight: 600;
  color: #666;
  letter-spacing: 1px;
}

.log-id {
  font-family: 'JetBrains Mono', monospace;
  font-size: 10px;
  color: #4a4a4a;
}

.log-content {
  height: 120px;
  overflow-y: auto;
  padding: 12px 16px;
}

.log-line {
  display: flex;
  gap: 12px;
  margin-bottom: 4px;
  font-family: 'JetBrains Mono', monospace;
  font-size: 11px;
  line-height: 1.5;
}

.log-time {
  color: #666;
  flex-shrink: 0;
}

.log-msg {
  color: #888;
}

/* Scrollbar */
.log-content::-webkit-scrollbar {
  width: 6px;
}

.log-content::-webkit-scrollbar-track {
  background: transparent;
}

.log-content::-webkit-scrollbar-thumb {
  background: #333;
  border-radius: 3px;
}

.scroll-container::-webkit-scrollbar {
  width: 8px;
}

.scroll-container::-webkit-scrollbar-track {
  background: transparent;
}

.scroll-container::-webkit-scrollbar-thumb {
  background: #ddd;
  border-radius: 4px;
}

.scroll-container::-webkit-scrollbar-thumb:hover {
  background: #ccc;
}
</style>
