<template>
  <!-- Step 05: 准备完成 -->
  <div class="step-card" ref="stepCardRef" :class="{ 'active': isActive, 'completed': isCompleted }">
    <div class="card-header">
      <div class="step-info">
        <span class="step-num">05</span>
        <span class="step-title">准备完成</span>
      </div>
      <div class="step-status">
        <span v-if="isCompleted" class="badge success">已完成</span>
        <span v-else-if="isActive" class="badge processing">进行中</span>
        <span v-else class="badge pending">等待</span>
      </div>
    </div>

    <div class="card-content">
      <p class="api-note">POST /api/simulation/start</p>
      <p class="description">模拟环境已准备完成，可以开始运行模拟</p>
      
      <!-- 模拟轮数配置 - 只有在配置生成完成且轮数计算出来后才显示 -->
      <div v-if="simulationConfig && autoGeneratedRounds" class="rounds-config-section">
        <div class="rounds-header">
          <div class="header-left">
            <span class="section-title">模拟轮数设定</span>
            <span class="section-desc">
              Multimo 自动规划推演现实 
              <span class="desc-highlight">{{ simulationConfig?.time_config?.total_simulation_hours || '-' }}</span> 小时，
              每轮代表现实 
              <span class="desc-highlight">{{ simulationConfig?.time_config?.minutes_per_round || '-' }}</span> 分钟时间流逝
            </span>
          </div>
          <label class="switch-control">
            <input type="checkbox" v-model="useCustomRoundsLocal">
            <span class="switch-track"></span>
            <span class="switch-label">自定义</span>
          </label>
        </div>
        
        <Transition name="fade" mode="out-in">
          <div v-if="useCustomRoundsLocal" class="rounds-content custom" key="custom">
            <div class="slider-display">
              <div class="slider-main-value">
                <span class="val-num">{{ customMaxRoundsLocal }}</span>
                <span class="val-unit">轮</span>
              </div>
              <div class="slider-meta-info">
                <span>若Agent规模为100：预计耗时约 {{ Math.round(customMaxRoundsLocal * 0.6) }} 分钟</span>
              </div>
            </div>

            <div class="range-wrapper">
              <input 
                type="range" 
                v-model.number="customMaxRoundsLocal" 
                min="10" 
                :max="autoGeneratedRounds"
                step="5"
                class="minimal-slider"
                :style="{ '--percent': ((customMaxRoundsLocal - 10) / (autoGeneratedRounds - 10)) * 100 + '%' }"
              />
              <div class="range-marks">
                <span>10</span>
                <span 
                  class="mark-recommend" 
                  :class="{ active: customMaxRoundsLocal === 40 }"
                  @click="customMaxRoundsLocal = 40"
                  :style="{ position: 'absolute', left: `calc(${(40 - 10) / (autoGeneratedRounds - 10) * 100}% - 30px)` }"
                >40 (推荐)</span>
                <span>{{ autoGeneratedRounds }}</span>
              </div>
            </div>
          </div>
          
          <div v-else class="rounds-content auto" key="auto">
            <div class="auto-info-card">
              <div class="auto-value">
                <span class="val-num">{{ autoGeneratedRounds }}</span>
                <span class="val-unit">轮</span>
              </div>
              <div class="auto-content">
                <div class="auto-meta-row">
                  <span class="duration-badge">
                    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                      <circle cx="12" cy="12" r="10"></circle>
                      <polyline points="12 6 12 12 16 14"></polyline>
                    </svg>
                    若Agent规模为100：预计耗时 {{ Math.round(autoGeneratedRounds * 0.6) }} 分钟
                  </span>
                </div>
                <div class="auto-desc">
                  <p class="highlight-tip" @click="useCustomRoundsLocal = true">
                    若首次运行，强烈建议切换至'自定义模式'减少模拟轮数，以便快速预览效果并降低报错风险 ➝
                  </p>
                </div>
              </div>
            </div>
          </div>
        </Transition>
      </div>

      <!-- 准备完成提示 -->
      <div v-if="isActive" class="completion-banner">
        <div class="banner-content">
          <span class="banner-icon">✓</span>
          <span class="banner-text">环境搭建已完成，可以开始模拟</span>
        </div>
      </div>

      <!-- 按钮区域 - 始终显示 -->
      <div class="action-group dual" :class="{ 'ready': isActive }">
        <button 
          class="action-btn secondary"
          @click="$emit('go-back')"
        >
          ← 返回图谱构建
        </button>
        <button 
          id="start-simulation-btn"
          class="action-btn primary"
          :class="{ 'pulse': isActive, 'highlight': isActive, 'disabled-state': !isActive }"
          :disabled="!isActive"
          @click="handleStart"
          style="min-height: 48px; font-size: 15px; font-weight: 600;"
        >
          <span v-if="isActive">
            <span class="btn-icon">🚀</span>
            开始双世界并行模拟
            <span class="btn-arrow">➝</span>
          </span>
          <span v-else>
            <span class="btn-waiting">⏳</span>
            等待准备完成...
          </span>
        </button>
      </div>
      
      <!-- 调试信息（开发环境） -->
      <div v-if="isDevelopment" class="debug-info">
        Phase: {{ phase }} | Active: {{ isActive }} | Config: {{ simulationConfig ? 'Yes' : 'No' }}
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, watch, nextTick, onMounted } from 'vue'

const props = defineProps({
  phase: {
    type: Number,
    required: true
  },
  simulationConfig: {
    type: Object,
    default: null
  },
  simulationMode: {
    type: String,
    default: 'manual'
  },
  simulationRounds: {
    type: Number,
    default: null
  }
})

const emit = defineEmits(['go-back', 'start-simulation'])

// 本地状态
const useCustomRoundsLocal = ref(false)
const customMaxRoundsLocal = ref(40)
const stepCardRef = ref(null)

// 检查是否准备完成：phase >= 4 或者所有步骤都已完成
// 检查是否为开发环境（安全的方式）
const isDevelopment = computed(() => {
  try {
    return import.meta.env?.DEV === true || import.meta.env?.MODE === 'development'
  } catch {
    return false
  }
})

const isActive = computed(() => {
  // 如果 phase >= 4，直接返回 true
  if (props.phase >= 4) return true
  // 如果有配置数据，也认为已完成（备用逻辑）
  if (props.simulationConfig?.time_config) return true
  return false
})
const isCompleted = computed(() => props.phase >= 4 || !!props.simulationConfig?.time_config)

// 当准备完成时，滚动到按钮位置
watch(() => props.phase, async (newPhase) => {
  if (newPhase >= 4) {
    await nextTick()
    if (stepCardRef.value) {
      // 延迟一下确保DOM已渲染
      setTimeout(() => {
        stepCardRef.value?.scrollIntoView({ behavior: 'smooth', block: 'center' })
      }, 300)
    }
  }
}, { immediate: true })

// 组件挂载时检查状态
onMounted(() => {
  // 调试日志
  console.log('[StepAutoPilotConfig] Mounted:', {
    phase: props.phase,
    isActive: isActive.value,
    hasConfig: !!props.simulationConfig,
    configTimeConfig: !!props.simulationConfig?.time_config
  })
  
  // 如果已完成，滚动到按钮位置
  if (props.phase >= 4 || props.simulationConfig?.time_config) {
    nextTick(() => {
      if (stepCardRef.value) {
        setTimeout(() => {
          stepCardRef.value?.scrollIntoView({ behavior: 'smooth', block: 'center' })
          // 尝试直接滚动到按钮
          const btn = document.getElementById('start-simulation-btn')
          if (btn) {
            setTimeout(() => {
              btn.scrollIntoView({ behavior: 'smooth', block: 'center' })
            }, 300)
          }
        }, 500)
      }
    })
  }
})

// 监听 phase 和 config 变化
watch([() => props.phase, () => props.simulationConfig], ([newPhase, newConfig]) => {
  console.log('[StepAutoPilotConfig] State changed:', {
    phase: newPhase,
    hasConfig: !!newConfig,
    isActive: isActive.value
  })
  
  if (newPhase >= 4 || newConfig?.time_config) {
    nextTick(() => {
      const btn = document.getElementById('start-simulation-btn')
      if (btn && isActive.value) {
        setTimeout(() => {
          btn.scrollIntoView({ behavior: 'smooth', block: 'center' })
        }, 300)
      }
    })
  }
}, { deep: true })

// 从配置中计算自动生成的轮数
const autoGeneratedRounds = computed(() => {
  if (!props.simulationConfig?.time_config) {
    return null
  }
  const totalHours = props.simulationConfig.time_config.total_simulation_hours
  const minutesPerRound = props.simulationConfig.time_config.minutes_per_round
  if (!totalHours || !minutesPerRound) {
    return null
  }
  const calculatedRounds = Math.floor((totalHours * 60) / minutesPerRound)
  // 确保最大轮数不小于40（推荐值）
  return Math.max(calculatedRounds, 40)
})

// 处理开始按钮点击
const handleStart = () => {
  const params = {}
  
  if (props.simulationMode === 'auto') {
    // 自动模式下，优先使用传入的 rounds
    params.maxRounds = props.simulationRounds || autoGeneratedRounds.value || 15
  } else if (useCustomRoundsLocal.value) {
    // 用户自定义轮数
    params.maxRounds = customMaxRoundsLocal.value
  }
  // 不传 maxRounds 时使用自动配置的轮数
  
  emit('start-simulation', params)
}

// 同步本地自定义轮数到合理范围
watch(autoGeneratedRounds, (newVal) => {
  if (newVal && customMaxRoundsLocal.value > newVal) {
    customMaxRoundsLocal.value = Math.min(40, newVal)
  }
})
</script>

<style scoped>
.step-card {
  background: #FFFFFF;
  border: 1px solid #E5E7EB;
  border-radius: 12px;
  margin-bottom: 16px;
  overflow: hidden;
  transition: all 0.3s ease;
}

.step-card.active {
  border-color: #000;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 16px 20px;
  background: #F9FAFB;
  border-bottom: 1px solid #E5E7EB;
}

.step-info {
  display: flex;
  align-items: center;
  gap: 12px;
}

.step-num {
  font-family: 'JetBrains Mono', monospace;
  font-size: 11px;
  font-weight: 600;
  color: #6B7280;
  background: #E5E7EB;
  padding: 4px 8px;
  border-radius: 4px;
}

.step-card.active .step-num {
  background: #000;
  color: #fff;
}

.step-title {
  font-size: 14px;
  font-weight: 600;
  color: #1F2937;
}

.badge {
  font-size: 11px;
  font-weight: 500;
  padding: 4px 10px;
  border-radius: 20px;
}

.badge.processing {
  background: #000;
  color: #fff;
}

.badge.pending {
  background: #F3F4F6;
  color: #9CA3AF;
}

.card-content {
  padding: 20px;
}

.api-note {
  font-family: 'JetBrains Mono', monospace;
  font-size: 11px;
  color: #6B7280;
  margin: 0 0 8px 0;
}

.description {
  font-size: 13px;
  color: #4B5563;
  margin: 0 0 16px 0;
  line-height: 1.5;
}

/* Rounds Config Section */
.rounds-config-section {
  background: #F9FAFB;
  border-radius: 12px;
  padding: 20px;
  margin-bottom: 20px;
}

.rounds-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: 16px;
}

.header-left {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.section-title {
  font-size: 14px;
  font-weight: 600;
  color: #1F2937;
}

.section-desc {
  font-size: 12px;
  color: #6B7280;
}

.desc-highlight {
  color: #000;
  font-weight: 600;
}

/* Switch Control */
.switch-control {
  display: flex;
  align-items: center;
  gap: 8px;
  cursor: pointer;
}

.switch-control input {
  display: none;
}

.switch-track {
  width: 36px;
  height: 20px;
  background: #E5E7EB;
  border-radius: 10px;
  position: relative;
  transition: background 0.2s;
}

.switch-track::after {
  content: '';
  position: absolute;
  top: 2px;
  left: 2px;
  width: 16px;
  height: 16px;
  background: #fff;
  border-radius: 50%;
  transition: transform 0.2s;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}

.switch-control input:checked + .switch-track {
  background: #000;
}

.switch-control input:checked + .switch-track::after {
  transform: translateX(16px);
}

.switch-label {
  font-size: 12px;
  color: #6B7280;
}

/* Rounds Content */
.rounds-content {
  animation: fadeIn 0.3s ease;
}

@keyframes fadeIn {
  from {
    opacity: 0;
    transform: translateY(-10px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

/* Custom Rounds */
.rounds-content.custom {
  padding: 16px;
  background: #fff;
  border-radius: 8px;
}

.slider-display {
  text-align: center;
  margin-bottom: 20px;
}

.slider-main-value {
  display: flex;
  align-items: baseline;
  justify-content: center;
  gap: 4px;
}

.val-num {
  font-size: 48px;
  font-weight: 700;
  color: #1F2937;
  line-height: 1;
}

.val-unit {
  font-size: 16px;
  color: #6B7280;
}

.slider-meta-info {
  margin-top: 8px;
}

.slider-meta-info span {
  font-size: 12px;
  color: #6B7280;
}

/* Range Slider */
.range-wrapper {
  position: relative;
  padding: 0 8px;
}

.minimal-slider {
  width: 100%;
  height: 6px;
  -webkit-appearance: none;
  appearance: none;
  background: linear-gradient(to right, #000 0%, #000 var(--percent, 50%), #E5E7EB var(--percent, 50%), #E5E7EB 100%);
  border-radius: 3px;
  outline: none;
}

.minimal-slider::-webkit-slider-thumb {
  -webkit-appearance: none;
  appearance: none;
  width: 20px;
  height: 20px;
  background: #000;
  border-radius: 50%;
  cursor: pointer;
  box-shadow: 0 2px 6px rgba(0, 0, 0, 0.2);
}

.minimal-slider::-moz-range-thumb {
  width: 20px;
  height: 20px;
  background: #000;
  border-radius: 50%;
  cursor: pointer;
  border: none;
  box-shadow: 0 2px 6px rgba(0, 0, 0, 0.2);
}

.range-marks {
  display: flex;
  justify-content: space-between;
  margin-top: 8px;
  position: relative;
}

.range-marks span {
  font-size: 11px;
  color: #9CA3AF;
}

.mark-recommend {
  cursor: pointer;
  color: #059669 !important;
  font-weight: 500;
}

.mark-recommend.active {
  color: #000 !important;
}

/* Auto Rounds */
.rounds-content.auto {
  padding: 16px;
  background: #fff;
  border-radius: 8px;
}

.auto-info-card {
  display: flex;
  gap: 20px;
  align-items: flex-start;
}

.auto-value {
  display: flex;
  align-items: baseline;
  gap: 4px;
  flex-shrink: 0;
}

.auto-content {
  flex: 1;
}

.auto-meta-row {
  margin-bottom: 8px;
}

.duration-badge {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  font-size: 12px;
  color: #6B7280;
  background: #F3F4F6;
  padding: 4px 10px;
  border-radius: 12px;
}

.duration-badge svg {
  flex-shrink: 0;
}

.auto-desc {
  margin-top: 8px;
}

.highlight-tip {
  font-size: 12px;
  color: #EA580C;
  cursor: pointer;
  margin: 0;
  transition: color 0.2s;
}

.highlight-tip:hover {
  color: #C2410C;
}

/* Action Group */
.action-group {
  display: flex;
  gap: 12px;
}

.action-group.dual {
  justify-content: space-between;
}

.action-group.ready {
  margin-top: 8px;
  padding-top: 16px;
  border-top: 2px solid #E5E7EB;
}

.action-btn {
  padding: 12px 24px;
  font-size: 14px;
  font-weight: 500;
  border-radius: 8px;
  cursor: pointer;
  transition: all 0.2s;
  border: none;
}

.action-btn.primary {
  background: #000;
  color: #fff;
}

.action-btn.primary:hover:not(:disabled) {
  background: #1F2937;
}

.action-btn.primary:disabled,
.action-btn.primary.disabled-state {
  background: #9CA3AF;
  cursor: not-allowed;
  opacity: 0.6;
}

.action-btn.primary.disabled-state:hover {
  transform: none;
  box-shadow: none;
}

.btn-waiting {
  display: inline-block;
  margin-right: 8px;
  font-size: 16px;
  animation: spin 2s linear infinite;
}

@keyframes spin {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}

.action-btn.primary.pulse {
  animation: pulse 2s infinite;
}

.action-btn.primary.highlight {
  background: linear-gradient(135deg, #000 0%, #1F2937 100%);
  box-shadow: 0 4px 16px rgba(0, 0, 0, 0.3);
  transform: scale(1.02);
  transition: all 0.3s ease;
}

.action-btn.primary.highlight:hover {
  transform: scale(1.05);
  box-shadow: 0 6px 20px rgba(0, 0, 0, 0.4);
}

.btn-icon {
  display: inline-block;
  margin-right: 8px;
  font-size: 18px;
}

.btn-arrow {
  display: inline-block;
  margin-left: 8px;
  font-size: 16px;
}

@keyframes pulse {
  0%, 100% {
    box-shadow: 0 0 0 0 rgba(0, 0, 0, 0.4);
  }
  50% {
    box-shadow: 0 0 0 12px rgba(0, 0, 0, 0);
  }
}

/* 完成横幅 */
.completion-banner {
  margin: 16px 0;
  padding: 16px;
  background: linear-gradient(135deg, #F0FDF4 0%, #D1FAE5 100%);
  border: 2px solid #86EFAC;
  border-radius: 12px;
  animation: slideDown 0.5s ease;
  box-shadow: 0 4px 12px rgba(34, 197, 94, 0.15);
}

.banner-content {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 12px;
}

.banner-icon {
  font-size: 24px;
  color: #16A34A;
  font-weight: bold;
}

.banner-text {
  font-size: 15px;
  color: #166534;
  font-weight: 600;
}

@keyframes slideDown {
  from {
    opacity: 0;
    transform: translateY(-20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.completion-hint {
  margin-top: 16px;
  padding: 12px 16px;
  background: #F0FDF4;
  border: 1px solid #86EFAC;
  border-radius: 8px;
  text-align: center;
  animation: fadeIn 0.5s ease;
}

.completion-hint p {
  margin: 0;
  font-size: 13px;
  color: #166534;
  font-weight: 500;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
}

.debug-info {
  margin-top: 8px;
  padding: 8px;
  background: #F3F4F6;
  border-radius: 4px;
  font-size: 11px;
  color: #6B7280;
  font-family: 'JetBrains Mono', monospace;
}

.action-btn.secondary {
  background: #F3F4F6;
  color: #4B5563;
}

.action-btn.secondary:hover {
  background: #E5E7EB;
}

/* Transitions */
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.3s ease, transform 0.3s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
  transform: translateY(-10px);
}
</style>
